#ifndef __MCC_ERROR_CODES__
#define __MCC_ERROR_CODES__

#define MCC_COULD_NOT_SET_VPARAM	0x07
#define MCC_COULD_NOT_GET_FPARAM	0x06
#define MCC_COULD_NOT_GET_VPARAM	0x05
#define MCC_COULD_NOT_GET_NEW_VPARAM	0x04
#define MCC_COULD_NOT_MAP_TO_SCREEN	0x03
#define MCC_COULD_NOT_CLAIM_TTY		0x02
#define MCC_SCREEN_SET_SUCCESS		0x01

#endif
